services:
  crudapp:
    image: hasan007/crudapp:latest
    ports:
      - 8080:80
      - 8081:80
    working_dir: /var/www/html/
    depends_on:
      - db
    networks:
      - default
    environment:
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASS}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS}"
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - default
