services:
  crudapp:
    image: hasan007/crudapp:latest
    ports:
      - 8080:80
      - 8081:80
    working_dir: /var/www/html/
    depends_on:
      - db
    networks:
      - default
    environment:
      DB_HOST: "db"
      DB_NAME: "dbcrudapp"
      DB_USER: "user"
      DB_PASS: "root"
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "dbcrudapp"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - default
