services:
  crudapp:
    image: crudapp
    ports:
      - 8080:80
      - 8081:80
    working_dir: /var/www/html/
    depends_on:
      - db
    networks:
      - default
    environment:
      DB_HOST: ""
      DB_NAME: ""
      DB_USER: ""
      DB_PASS: ""
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ""
      MYSQL_USER: ""
      MYSQL_PASSWORD: ""
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - default
