apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudapp-deployment
  labels:
    name: crudapp-deployment
    app: demo-crudapp
    type: front-end
spec:
  template:
    metadata:
      name: crudapp-pod
      labels:
        name: crudapp-pod
        app: demo-crudapp
        type: front-end
    spec:
      containers:
        - name: crudapp
          image: hasan007/crudapp
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_NAME
              value: "dbcrudapp"
            - name: DB_USER
              value: "user"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql-dbpass
                  key: dbpass
  replicas: 2
  selector:
    matchLabels:
      type: front-end
