apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql-pod
    app: demo-crudapp
spec:
  containers:
    - name: mysql
      image: mysql:8.0
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_DATABASE
          value: "dbcrudapp"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "root"
        - name: MYSQL_ROOT_PASSWORD
          value: "password"