apiVersion: v1
kind: Service
metadata:
  name: crudapp-service
  labels:
    name: crudapp-service
    app: demo-crudapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
  selector:
    name: crudapp-pod
    app: demo-crudapp